### DISCUSSION TITLE
Reach study shows incorrect IK solutions

### DISCUSSION THREAD

**Discussion by vicltz** [ros-industrial/reach_ros#12] [Q&A]
I am trying to do a reach study of the [TIAGo robot](http://wiki.ros.org/Robots/TIAGo), you can find the URDF [here.](https://github.com/pal-robotics/tiago_robot/blob/kinetic-devel/tiago_description/robots/tiago.urdf.xacro). It uses a gripper as end effector , you can find the urdf of the gripper [here](https://github.com/pal-robotics/pal_gripper/tree/humble-devel).

However I struggle to make it work, and I am not sure if it is because of misconfiguration or some bug with the package.

At the end of the analysis, some interactive markers are broken and lead to impossible pose of the robot.

These are the groups defined in the srdf file of the robot:
```

<group name="arm">
        <joint name="arm_1_joint" />
        <joint name="arm_2_joint" />
        <joint name="arm_3_joint" />
        <joint name="arm_4_joint" />
        <joint name="arm_5_joint" />
        <joint name="arm_6_joint" />
        <joint name="arm_7_joint" />
        <joint name="arm_tool_joint" />
    </group>

    <group name="arm_torso">
        <joint name="torso_lift_joint" />
        <joint name="arm_1_joint" />
        <joint name="arm_2_joint" />
        <joint name="arm_3_joint" />
        <joint name="arm_4_joint" />
        <joint name="arm_5_joint" />
        <joint name="arm_6_joint" />
        <joint name="arm_7_joint" />
        <joint name="arm_tool_joint" />
    </group>

    <group name="gripper">
        <link name="gripper_left_finger_link" />
        <link name="gripper_right_finger_link" />
        <link name="gripper_link" />
        <joint name="gripper_left_finger_joint" />
        <joint name="gripper_right_finger_joint" />
    </group>

    <group name="manipulator">
        <joint name="torso_lift_joint" />
        <joint name="arm_1_joint" />
        <joint name="arm_2_joint" />
        <joint name="arm_3_joint" />
        <joint name="arm_4_joint" />
        <joint name="arm_5_joint" />
        <joint name="arm_6_joint" />
        <joint name="arm_7_joint" />
        <joint name="arm_tool_joint" />
        <link name="tcp" />
    </group>

```

I added a TCP link to my end effector URDF (gripper urdf) like in the demo:
```
  <link name="tcp"/>
  <joint name="gripper_base_link_to_tcp" type="fixed">
    <parent link="gripper_base_link"/>
    <child link="tcp"/>
    <origin xyz="0 0 0.26" rpy="0 0 0"/>
  </joint>
```

Most of the interactive makers work, but a small number of them are just acting weird:

example of working marker :
![image](https://github.com/ros-industrial/reach_ros/assets/19519240/71cc4f05-d601-4531-bcec-fb88457c7646)

example of broken marker:

![image](https://github.com/ros-industrial/reach_ros/assets/19519240/2429d9e8-a059-47b8-aad4-789e81c97952)

This is the pose of the robot I get when clicking on the green marker on the extreme right.

All the markers at the extreme left (relatively to the robot orientation) seem broken:

![image](https://github.com/ros-industrial/reach_ros/assets/19519240/bb2d7c79-6a2c-4bab-9f25-f724862df157)

Here is my yaml config file:

```
optimization:
  radius: 0.2
  max_steps: 15
  step_improvement_threshold: 0.01

ik_solver:
  name: MoveItIKSolver
  distance_threshold: 0.0
  planning_group: manipulator
  collision_mesh_filename: package://reach_ros/demo/config/part.ply
  touch_links: []

evaluator:
  name: MultiplicativeEvaluator
  plugins:
    - name: ManipulabilityMoveIt
      planning_group: manipulator
    - name: DistancePenaltyMoveIt
      planning_group: manipulator
      distance_threshold: 0.0
      exponent: 2
      collision_mesh_filename: package://reach_ros/demo/config/part.ply
      touch_links: []

display:
  name: ROSDisplay
  collision_mesh_filename: package://reach_ros/demo/config/part.ply
  kinematic_base_frame: base_footprint
  marker_scale: 0.05

target_pose_generator:
  name: PointCloudTargetPoseGenerator
  pcd_file: package://reach_ros/demo/config/part.pcd
  points_frame: base_footprint
  target_frame: base_footprint

logger:
  name: BoostProgressConsoleLogger



```
Here is the kinematics config file:

```
arm_torso:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

```

One other thing to notice is that the results are highly asymmetrical while the scene and the robot are symmetrical.

The only asymmetrical thing I know is that:

This is the pose of the robot with zero angle on each joint:

![image](https://github.com/ros-industrial/reach_ros/assets/19519240/0e4d84b2-1105-4706-928a-dc8fae54b06f)

But when the robot is launched into RVIZ the pose of the robot is like this (arm in front of him)

![image](https://github.com/ros-industrial/reach_ros/assets/19519240/b63ebf93-140f-4efc-bae2-1aa81778acf6)

I am not sure why this happens and if this is normal ?

Thank you for your help
